export const VENUES = [
  {
    apiName: 'Atlanta Stadium',
    name: 'Mercedes-Benz Stadium',
    pin: 'ATL',
    city: 'Atlanta',
    state: 'Georgia',
    country: 'USA',
    lat: 33.7554,
    lng: -84.4010,
    capacity: 71_000,
    surface: 'FieldTurf',
    built: 1992,
    roof: 'Retractable',
    homeClub: 'Atlanta Falcons, Atlanta United FC',
    timezone: 'America/New_York',
  },
  {
    apiName: 'BC Place Vancouver',
    name: 'BC Place',
    pin: 'VAN',
    city: 'Vancouver',
    state: 'British Columbia',
    country: 'CAN',
    lat: 49.2767,
    lng: -123.1115,
    capacity: 54_500,
    surface: 'FieldTurf',
    built: 1983,
    roof: 'Retractable',
    homeClub: 'Vancouver Whitecaps FC',
    timezone: 'America/Vancouver',
  },
  {
    apiName: 'Boston Stadium',
    name: 'Gillette Stadium',
    pin: 'BOS',
    city: 'Boston',
    state: 'Massachusetts',
    country: 'USA',
    lat: 42.0909,
    lng: -71.2643,
    capacity: 65_878,
    surface: 'Natural grass',
    built: 2002,
    roof: 'Open',
    homeClub: 'New England Patriots, New England Revolution',
    timezone: 'America/New_York',
  },
  {
    apiName: 'Dallas Stadium',
    name: 'AT&T Stadium',
    pin: 'DAL',
    city: 'Dallas',
    state: 'Texas',
    country: 'USA',
    lat: 32.7478,
    lng: -97.0928,
    capacity: 80_000,
    surface: 'Natural grass',
    built: 2009,
    roof: 'Retractable',
    homeClub: 'Dallas Cowboys',
    timezone: 'America/Chicago',
  },
  {
    apiName: 'Guadalajara Stadium',
    name: 'Estadio Akron',
    pin: 'GDL',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'MEX',
    lat: 20.6868,
    lng: -103.4697,
    capacity: 49_850,
    surface: 'Natural grass',
    built: 2010,
    roof: 'Open',
    homeClub: 'Club Deportivo Guadalajara',
    timezone: 'America/Mexico_City',
  },
  {
    apiName: 'Houston Stadium',
    name: 'NRG Stadium',
    pin: 'HOU',
    city: 'Houston',
    state: 'Texas',
    country: 'USA',
    lat: 29.6847,
    lng: -95.4107,
    capacity: 72_220,
    surface: 'Natural grass',
    built: 2002,
    roof: 'Retractable',
    homeClub: 'Houston Texans',
    timezone: 'America/Chicago',
  },
  {
    apiName: 'Kansas City Stadium',
    name: 'Arrowhead Stadium',
    pin: 'KC',
    city: 'Kansas City',
    state: 'Missouri',
    country: 'USA',
    lat: 39.0489,
    lng: -94.4839,
    capacity: 76_416,
    surface: 'Natural grass',
    built: 1972,
    roof: 'Open',
    homeClub: 'Kansas City Chiefs',
    timezone: 'America/Chicago',
  },
  {
    apiName: 'Los Angeles Stadium',
    name: 'SoFi Stadium',
    pin: 'LA',
    city: 'Los Angeles',
    state: 'California',
    country: 'USA',
    lat: 33.9535,
    lng: -118.3392,
    capacity: 70_240,
    surface: 'Natural grass',
    built: 2020,
    roof: 'Open canopy',
    homeClub: 'LA Rams, LA Chargers',
    timezone: 'America/Los_Angeles',
  },
  {
    apiName: 'Mexico City Stadium',
    name: 'Estadio Azteca',
    pin: 'MEX',
    city: 'Mexico City',
    state: 'CDMX',
    country: 'MEX',
    lat: 19.3029,
    lng: -99.1505,
    capacity: 87_523,
    surface: 'Natural grass',
    built: 1966,
    roof: 'Open',
    homeClub: 'Club América, Cruz Azul',
    timezone: 'America/Mexico_City',
  },
  {
    apiName: 'Miami Stadium',
    name: 'Hard Rock Stadium',
    pin: 'MIA',
    city: 'Miami',
    state: 'Florida',
    country: 'USA',
    lat: 25.9580,
    lng: -80.2389,
    capacity: 65_326,
    surface: 'Natural grass',
    built: 1987,
    roof: 'Open canopy',
    homeClub: 'Miami Dolphins, Inter Miami CF',
    timezone: 'America/New_York',
  },
  {
    apiName: 'Monterrey Stadium',
    name: 'Estadio BBVA',
    pin: 'MTY',
    city: 'Monterrey',
    state: 'Nuevo León',
    country: 'MEX',
    lat: 25.6691,
    lng: -100.2458,
    capacity: 53_500,
    surface: 'Natural grass',
    built: 2015,
    roof: 'Open',
    homeClub: 'CF Monterrey',
    timezone: 'America/Monterrey',
  },
  {
    apiName: 'New York/New Jersey Stadium',
    name: 'MetLife Stadium',
    pin: 'NY',
    city: 'New York / New Jersey',
    state: 'New Jersey',
    country: 'USA',
    lat: 40.8135,
    lng: -74.0745,
    capacity: 82_500,
    surface: 'Natural grass',
    built: 2010,
    roof: 'Open',
    homeClub: 'NY Giants, NY Jets',
    timezone: 'America/New_York',
  },
  {
    apiName: 'Philadelphia Stadium',
    name: 'Lincoln Financial Field',
    pin: 'PHI',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    country: 'USA',
    lat: 39.9009,
    lng: -75.1675,
    capacity: 69_796,
    surface: 'Natural grass',
    built: 2003,
    roof: 'Open',
    homeClub: 'Philadelphia Eagles',
    timezone: 'America/New_York',
  },
  {
    apiName: 'San Francisco Bay Area Stadium',
    name: "Levi's Stadium",
    pin: 'SF',
    city: 'San Francisco Bay Area',
    state: 'California',
    country: 'USA',
    lat: 37.4032,
    lng: -121.9698,
    capacity: 68_500,
    surface: 'Natural grass',
    built: 2014,
    roof: 'Open',
    homeClub: 'San Francisco 49ers',
    timezone: 'America/Los_Angeles',
  },
  {
    apiName: 'Seattle Stadium',
    name: 'Lumen Field',
    pin: 'SEA',
    city: 'Seattle',
    state: 'Washington',
    country: 'USA',
    lat: 47.5952,
    lng: -122.3316,
    capacity: 69_000,
    surface: 'FieldTurf',
    built: 2002,
    roof: 'Open canopy',
    homeClub: 'Seattle Seahawks, Seattle Sounders FC',
    timezone: 'America/Los_Angeles',
  },
  {
    apiName: 'Toronto Stadium',
    name: 'BMO Field',
    pin: 'TOR',
    city: 'Toronto',
    state: 'Ontario',
    country: 'CAN',
    lat: 43.6333,
    lng: -79.4189,
    capacity: 30_000,
    surface: 'Natural grass',
    built: 2007,
    roof: 'Open',
    homeClub: 'Toronto FC',
    timezone: 'America/Toronto',
  },
];

export const VENUE_BY_API_NAME = Object.fromEntries(VENUES.map((v) => [v.apiName, v]));

export const COUNTRY_FLAG = { USA: '🇺🇸', CAN: '🇨🇦', MEX: '🇲🇽' };

const WMO_ICON = {
  0: '☀️', 1: '🌤️', 2: '⛅', 3: '☁️',
  45: '🌫️', 48: '🌫️',
  51: '🌦️', 53: '🌦️', 55: '🌦️',
  61: '🌧️', 63: '🌧️', 65: '🌧️',
  71: '❄️', 73: '❄️', 75: '❄️', 77: '🌨️',
  80: '🌧️', 81: '🌧️', 82: '🌧️',
  85: '🌨️', 86: '🌨️',
  95: '⛈️', 96: '⛈️', 99: '⛈️',
};

export function weatherIcon(code) {
  return WMO_ICON[code] ?? '🌡️';
}
